# Generated by Django 3.2.7 on 2021-09-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210918_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highestBid',
            field=models.IntegerField(default=1),
        ),
    ]
